export function createMeteorSystem({world,components,THREE,scene,terrain,locus}){
 const {Transform,RenderObject,Meteor,MeteorShower,Body,Locus}=components; let serial=0; const fx=[];
 const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
 class RNG{constructor(s=1){this.s=s>>>0||1}next(){let x=this.s;x^=x<<13;x^=x>>>17;x^=x<<5;this.s=x>>>0;return this.s/4294967296}}
 const targetAt=(x=0,z=0)=>{const h=terrain.terrainHeight(x,z);return new THREE.Vector3(x,Number.isFinite(h)?h:terrain.groundHeight(x,z),z)};
 function dispose(o){scene.remove(o);o.geometry?.dispose?.();if(Array.isArray(o.material))o.material.forEach(m=>m.dispose?.());else o.material?.dispose?.()}
 function launch(target=targetAt(),power=1){const r=new RNG(((++serial+17)*991)>>>0),start=target.clone().add(new THREE.Vector3((r.next()-.5)*2.4,10+r.next()*3.2,(r.next()-.5)*2.4)),id=world.entity();
  const head=new THREE.Mesh(new THREE.SphereGeometry(.28,7,5),new THREE.MeshBasicMaterial({color:0xffd08a})),trail=new THREE.Line(new THREE.BufferGeometry().setFromPoints([start,start.clone().lerp(target,.22)]),new THREE.LineBasicMaterial({color:0xff7b42,transparent:true,opacity:.78,depthWrite:false,blending:THREE.AdditiveBlending}));scene.add(head,trail);
  world.add(id,Transform,{position:start.clone(),rotation:new THREE.Euler(),scale:new THREE.Vector3(1,1,1),visible:true});world.add(id,RenderObject,{object:head});world.add(id,Meteor,{start,target:target.clone(),power,born:performance.now(),life:300+r.next()*100,trail});if(Locus)world.add(id,Locus,{id:locus});return id}
 function impulse(center,power){for(const id of world.query(Transform,Body)){if(Meteor.has(id))continue;const t=Transform.get(id);if(!t.velocity)continue;const d=t.position.clone().sub(center),dist=Math.max(.25,d.length());if(dist>3.2)continue;d.y=Math.max(.45,d.y+.7);d.normalize();t.velocity.addScaledVector(d,Math.max(0,3.8*power*(1-dist/3.4)))}}
 function impactFx(center){const r=new RNG((++serial*2654435761)>>>0),now=performance.now(),dummy=new THREE.Object3D(),heatGeo=new THREE.SphereGeometry(.07,5,4),heatMat=new THREE.MeshBasicMaterial({color:0xff4b20,transparent:true,opacity:.72,depthWrite:false,blending:THREE.AdditiveBlending}),heat=new THREE.InstancedMesh(heatGeo,heatMat,24);
  for(let i=0;i<24;i++){let x,y,z,q;do{x=(r.next()*2-1)*1.25;y=(r.next()*2-1)*.9;z=(r.next()*2-1)*1.25;q=x*x/1.5625+y*y/.81+z*z/1.5625}while(q>1);dummy.position.set(x,Math.abs(y)*.72-.3,z);dummy.scale.setScalar(.5+r.next()*1.25);dummy.updateMatrix();heat.setMatrixAt(i,dummy.matrix)}heat.position.copy(center);heat.instanceMatrix.needsUpdate=true;scene.add(heat);fx.push({kind:"heat",mesh:heat,mat:heatMat,born:now,life:1900,opacity:.72});
  const geo=new THREE.IcosahedronGeometry(1,1),mat=new THREE.MeshStandardMaterial({color:0x665f55,roughness:1,transparent:true,opacity:.82,depthWrite:false}),smoke=new THREE.InstancedMesh(geo,mat,9),origins=[],vel=[],scales=[];for(let i=0;i<9;i++){const a=r.next()*Math.PI*2,rr=.12+Math.sqrt(r.next())*.8,p=new THREE.Vector3(Math.cos(a)*rr,r.next()*.45,Math.sin(a)*rr),v=new THREE.Vector3(Math.cos(a)*(.3+r.next()*.5),.6+r.next()*.7,Math.sin(a)*(.3+r.next()*.5)),s=.28+r.next()*.4;origins.push(p);vel.push(v);scales.push(s);dummy.position.copy(p);dummy.scale.setScalar(s*.2);dummy.updateMatrix();smoke.setMatrixAt(i,dummy.matrix)}smoke.position.copy(center);smoke.instanceMatrix.needsUpdate=true;scene.add(smoke);fx.push({kind:"smoke",mesh:smoke,mat,born:now,life:1050,opacity:.82,origins,vel,scales,dummy});while(fx.length>80)dispose(fx.shift().mesh)}
 function removeMeteor(id){const m=Meteor.get(id),ro=RenderObject.get(id);if(m)dispose(m.trail);if(ro?.object)dispose(ro.object);world.destroy(id)}
 function impact(id,point,power,canChangeTerrain){if(canChangeTerrain)terrain.crater(point,{radius:2.15*Math.max(.55,Math.sqrt(power)),depth:1.45*power,rim:.34*power});impulse(point,power);impactFx(point);removeMeteor(id)}
 function meteor(center=targetAt()){return launch(center,1)}
 function meteors(center=targetAt()){const id=world.entity(),r=new RNG((++serial*2246822519)>>>0),delays=[];let total=0;for(let i=0;i<9;i++){const d=170+r.next()*330;delays.push(d);total+=d}const scale=2900/Math.max(1,total);delays.forEach((d,i)=>delays[i]=d*scale);world.add(id,MeteorShower,{center:center.clone(),remaining:10,next:performance.now()+80,rng:r,delays,index:0});if(Locus)world.add(id,Locus,{id:locus});return id}
 function updateFx(now){for(let i=fx.length-1;i>=0;i--){const f=fx[i],u=(now-f.born)/f.life;if(u>=1){dispose(f.mesh);fx.splice(i,1);continue}if(f.kind==="heat"){f.mat.opacity=f.opacity*(1-u)*(.9+.1*Math.sin(now*.018+i));f.mesh.scale.setScalar(1+u*.08)}else{const erupt=Math.min(1,u/.16),fade=u<.28?1:Math.max(0,1-(u-.28)/.72);f.mat.opacity=f.opacity*fade;for(let j=0;j<f.origins.length;j++){const p=f.origins[j],v=f.vel[j],travel=u*1.8,grow=f.scales[j]*(.2+1.5*erupt+.7*u);f.dummy.position.set(p.x+v.x*travel,p.y+v.y*travel+.45*u*u,p.z+v.z*travel);f.dummy.scale.set(grow,grow*(.72+.28*u),grow);f.dummy.rotation.set(j*.71+u*.8,j*.43-u*.55,j*.29+u*.35);f.dummy.updateMatrix();f.mesh.setMatrixAt(j,f.dummy.matrix)}f.mesh.instanceMatrix.needsUpdate=true}}}
 function update(now){for(const id of world.query(Transform,Meteor)){const t=Transform.get(id),m=Meteor.get(id),u=clamp((now-m.born)/m.life,0,1),e=1-Math.pow(1-u,2),prev=t.position.clone(),next=m.start.clone().lerp(m.target,e),hit=terrain.segmentApparatusHit(prev,next);if(hit){t.position.copy(hit.point);impact(id,hit.point,m.power,false);continue}t.position.copy(next);m.trail.geometry.setFromPoints([m.start.clone().lerp(m.target,Math.max(0,e-.16)),next]);m.trail.material.opacity=.78*(1-u*.45);if(u>=1)impact(id,m.target,m.power,true)}
  for(const id of world.query(MeteorShower)){const s=MeteorShower.get(id);if(now<s.next)continue;const a=s.rng.next()*Math.PI*2,rr=Math.sqrt(s.rng.next())*1.15,x=s.center.x+Math.cos(a)*rr,z=s.center.z+Math.sin(a)*rr,p=terrain.insideMaterial(x,z)?targetAt(x,z):targetAt(s.center.x,s.center.z);launch(p,.38);s.remaining--;if(s.remaining<=0)world.destroy(id);else s.next=now+s.delays[s.index++]}
  updateFx(now)}
 return{meteor,meteors,launch,targetAt,update,inspect:()=>({falling:world.query(Meteor).length,showers:world.query(MeteorShower).length,impactFx:fx.length})}
}
