const SQRT1_2=Math.SQRT1_2;
export function createTerrainSystem({THREE,scene}){
  const NX=30,NY=22,NZ=30,MIN=new THREE.Vector3(-10,-5.5,-10),MAX=new THREE.Vector3(10,6.5,10);
  const APPARATUS_RADIUS=9.75,APPARATUS_APOTHEM=APPARATUS_RADIUS*Math.cos(Math.PI/8),EDGE_REVEAL=.7,MATERIAL_APOTHEM=APPARATUS_APOTHEM-EDGE_REVEAL;
  const APPARATUS_TOP=-1.1,APPARATUS_DEPTH=5,APPARATUS_BOTTOM=APPARATUS_TOP-APPARATUS_DEPTH,SURFACE_Y=.15;
  const PLANES=[[1,0],[-1,0],[0,1],[0,-1],[SQRT1_2,SQRT1_2],[-SQRT1_2,SQRT1_2],[SQRT1_2,-SQRT1_2],[-SQRT1_2,-SQRT1_2]];
  const field=new Float32Array(NX*NY*NZ),initial=new Float32Array(field.length),idx=(x,y,z)=>x+NX*(y+NY*z);
  const wp=(x,y,z)=>new THREE.Vector3(THREE.MathUtils.lerp(MIN.x,MAX.x,x/(NX-1)),THREE.MathUtils.lerp(MIN.y,MAX.y,y/(NY-1)),THREE.MathUtils.lerp(MIN.z,MAX.z,z/(NZ-1)));
  const octagonDistance=(x,z)=>Math.max(Math.abs(x),Math.abs(z),(Math.abs(x)+Math.abs(z))/Math.SQRT2);
  const insideMaterial=(x,z)=>octagonDistance(x,z)<=MATERIAL_APOTHEM+1e-6,insideApparatus=(x,z,pad=0)=>octagonDistance(x,z)<=APPARATUS_APOTHEM+pad;
  function boundary(x,z){let q=-Infinity,nx=0,nz=0;for(const[px,pz]of PLANES){const d=x*px+z*pz;if(d>q){q=d;nx=px;nz=pz}}return{q,nx,nz};}
  function clipPlane(poly,nx,nz){if(!poly.length)return poly;const out=[];let a=poly.at(-1),da=a.x*nx+a.z*nz-MATERIAL_APOTHEM,ain=da<=1e-6;for(const b of poly){const db=b.x*nx+b.z*nz-MATERIAL_APOTHEM,bin=db<=1e-6;if(ain!==bin){const t=da/(da-db);out.push(a.clone().lerp(b,t))}if(bin)out.push(b);a=b;da=db;ain=bin}return out;}
  function clip(raw){const out=[];for(let i=0;i<raw.length;i+=3){let poly=[raw[i],raw[i+1],raw[i+2]];for(const[nx,nz]of PLANES){poly=clipPlane(poly,nx,nz);if(poly.length<3)break}for(let j=1;j+1<poly.length;j++)out.push(poly[0],poly[j],poly[j+1])}return out;}
  function cutWalls(surface){const edges=new Map(),eps=1e-4,key=p=>`${Math.round(p.x*1e4)},${Math.round(p.y*1e4)},${Math.round(p.z*1e4)}`;function planeFor(a,b){for(let i=0;i<PLANES.length;i++){const[nx,nz]=PLANES[i];if(Math.abs(a.x*nx+a.z*nz-MATERIAL_APOTHEM)<eps&&Math.abs(b.x*nx+b.z*nz-MATERIAL_APOTHEM)<eps)return i}return-1}for(let i=0;i<surface.length;i+=3){const tri=[surface[i],surface[i+1],surface[i+2]];for(let j=0;j<3;j++){const a=tri[j],b=tri[(j+1)%3],p=planeFor(a,b);if(p<0)continue;const ka=key(a),kb=key(b),id=p+":"+(ka<kb?ka+"|"+kb:kb+"|"+ka);if(!edges.has(id))edges.set(id,[a.clone(),b.clone()])}}const walls=[];for(const[a,b]of edges.values()){const fy=Math.min(APPARATUS_TOP-.03,a.y,b.y),ad=new THREE.Vector3(a.x,fy,a.z),bd=new THREE.Vector3(b.x,fy,b.z);walls.push(a,b,bd,a,bd,ad)}return walls;}
  const corners=[[0,0,0],[1,0,0],[1,1,0],[0,1,0],[0,0,1],[1,0,1],[1,1,1],[0,1,1]],tets=[[0,5,1,6],[0,1,2,6],[0,2,3,6],[0,3,7,6],[0,7,4,6],[0,4,5,6]];
  const interp=(a,b,va,vb)=>a.clone().lerp(b,THREE.MathUtils.clamp(va/(va-vb),0,1));
  function polygonize(ps,vs,out){const inside=[],outside=[];for(let i=0;i<4;i++)(vs[i]>0?inside:outside).push(i);if(!inside.length||inside.length===4)return;if(inside.length===1||inside.length===3){const inv=inside.length===3,A=inv?outside[0]:inside[0],others=inv?inside:outside,p0=interp(ps[A],ps[others[0]],vs[A],vs[others[0]]),p1=interp(ps[A],ps[others[1]],vs[A],vs[others[1]]),p2=interp(ps[A],ps[others[2]],vs[A],vs[others[2]]);out.push(...(inv?[p0,p2,p1]:[p0,p1,p2]));return}const[a,b]=inside,[c,d]=outside,p0=interp(ps[a],ps[c],vs[a],vs[c]),p1=interp(ps[a],ps[d],vs[a],vs[d]),p2=interp(ps[b],ps[c],vs[b],vs[c]),p3=interp(ps[b],ps[d],vs[b],vs[d]);out.push(p0,p1,p2,p2,p1,p3);}
  for(let z=0;z<NZ;z++)for(let y=0;y<NY;y++)for(let x=0;x<NX;x++){const p=wp(x,y,z);field[idx(x,y,z)]=SURFACE_Y-p.y;}initial.set(field);
  const geometry=new THREE.BufferGeometry(),material=new THREE.MeshStandardMaterial({color:0x785846,roughness:.96,metalness:.02,flatShading:true,side:THREE.DoubleSide}),mesh=new THREE.Mesh(geometry,material);mesh.name="deformable-world-substance";mesh.receiveShadow=true;scene.add(mesh);
  const apparatusMaterial=new THREE.MeshStandardMaterial({color:0x3f4745,roughness:.78,metalness:.22}),apparatus=new THREE.Mesh(new THREE.CylinderGeometry(APPARATUS_RADIUS,APPARATUS_RADIUS,APPARATUS_DEPTH,8,1,false,Math.PI/8),apparatusMaterial);apparatus.position.y=APPARATUS_TOP-APPARATUS_DEPTH*.5;apparatus.name="crucible-octagonal-apparatus";apparatus.receiveShadow=true;scene.add(apparatus);
  const G=112,support=new Float32Array(G*G);
  function rasterize(out){support.fill(-Infinity);const gx=x=>THREE.MathUtils.clamp((x-MIN.x)/(MAX.x-MIN.x)*(G-1),0,G-1),gz=z=>THREE.MathUtils.clamp((z-MIN.z)/(MAX.z-MIN.z)*(G-1),0,G-1),eps=1e-8;for(let t=0;t<out.length;t+=3){const a=out[t],b=out[t+1],c=out[t+2],den=(b.z-c.z)*(a.x-c.x)+(c.x-b.x)*(a.z-c.z);if(Math.abs(den)<eps)continue;for(let iz=Math.max(0,Math.floor(gz(Math.min(a.z,b.z,c.z)))-1);iz<=Math.min(G-1,Math.ceil(gz(Math.max(a.z,b.z,c.z)))+1);iz++){const z=THREE.MathUtils.lerp(MIN.z,MAX.z,iz/(G-1));for(let ix=Math.max(0,Math.floor(gx(Math.min(a.x,b.x,c.x)))-1);ix<=Math.min(G-1,Math.ceil(gx(Math.max(a.x,b.x,c.x)))+1);ix++){const x=THREE.MathUtils.lerp(MIN.x,MAX.x,ix/(G-1)),wa=((b.z-c.z)*(x-c.x)+(c.x-b.x)*(z-c.z))/den,wb=((c.z-a.z)*(x-c.x)+(a.x-c.x)*(z-c.z))/den,wc=1-wa-wb;if(wa>=-1e-5&&wb>=-1e-5&&wc>=-1e-5){const y=wa*a.y+wb*b.y+wc*c.y,k=ix+G*iz;if(y>support[k])support[k]=y}}}}for(let pass=0;pass<2;pass++){const copy=support.slice();for(let z=1;z<G-1;z++)for(let x=1;x<G-1;x++){const k=x+G*z;if(Number.isFinite(copy[k]))continue;let h=-Infinity;for(let dz=-1;dz<=1;dz++)for(let dx=-1;dx<=1;dx++)h=Math.max(h,copy[x+dx+G*(z+dz)]);if(Number.isFinite(h))support[k]=h}}}
  function terrainHeight(x,z){if(!insideMaterial(x,z))return-Infinity;const fx=THREE.MathUtils.clamp((x-MIN.x)/(MAX.x-MIN.x)*(G-1),0,G-1.001),fz=THREE.MathUtils.clamp((z-MIN.z)/(MAX.z-MIN.z)*(G-1),0,G-1.001),ix=Math.floor(fx),iz=Math.floor(fz);return Math.max(support[ix+G*iz],support[ix+1+G*iz],support[ix+G*(iz+1)],support[ix+1+G*(iz+1)]);}
  function groundHeight(x,z){const h=terrainHeight(x,z);return insideApparatus(x,z)?Math.max(h,APPARATUS_TOP):h;}
  let triangles=0;
  function rebuild(){const raw=[];for(let z=0;z<NZ-1;z++)for(let y=0;y<NY-1;y++)for(let x=0;x<NX-1;x++){const ps=corners.map(c=>wp(x+c[0],y+c[1],z+c[2])),vs=corners.map(c=>field[idx(x+c[0],y+c[1],z+c[2])]);for(const t of tets)polygonize(t.map(i=>ps[i]),t.map(i=>vs[i]),raw)}const out=clip(raw);out.push(...cutWalls(out));rasterize(out);const pos=[];for(const p of out)pos.push(p.x,p.y,p.z);geometry.setAttribute("position",new THREE.Float32BufferAttribute(pos,3));geometry.computeVertexNormals();geometry.computeBoundingSphere();triangles=out.length/3;}
  function mutateSphere(center,radius,amount,verticalScale=1){for(let z=1;z<NZ-1;z++)for(let y=1;y<NY-1;y++)for(let x=1;x<NX-1;x++){const p=wp(x,y,z),dx=p.x-center.x,dy=(p.y-center.y)/verticalScale,dz=p.z-center.z,d=Math.hypot(dx,dy,dz);if(d>=radius)continue;const w=1-d/radius;field[idx(x,y,z)]+=amount*w*w;}}
  function dent(center,{radius=1.5,depth=.42}={}){mutateSphere(center,radius,-depth,.48);rebuild();}
  function bite(center,{radius=1.45,depth=1.05}={}){mutateSphere(center,radius,-depth,.9);rebuild();}
  function crater(center,{radius=2.15,depth=1.45,rim=.34}={}){
    for(let z=1;z<NZ-1;z++)for(let y=1;y<NY-1;y++)for(let x=1;x<NX-1;x++){
      const p=wp(x,y,z),dx=p.x-center.x,dz=p.z-center.z,radial=Math.hypot(dx,dz),dy=p.y-center.y;
      const bowl=Math.hypot(dx,dy*.82,dz);if(bowl<radius*.72){const w=1-bowl/(radius*.72);field[idx(x,y,z)]-=depth*w*w;}
      if(radial>radius*.62&&radial<radius&&Math.abs(dy)<radius*.48){const ring=Math.sin(Math.PI*(radial-radius*.62)/(radius*.38)),vertical=Math.max(0,1-Math.abs(dy-radius*.08)/(radius*.48));field[idx(x,y,z)]+=rim*ring*vertical;}
    }
    rebuild();
  }
  function reset(){field.set(initial);rebuild();}
  function collideSphere(position,velocity,radius,restitution=.28,drag=.86){if(position.y-radius>=APPARATUS_TOP||position.y+radius<=APPARATUS_BOTTOM)return false;const b=boundary(position.x,position.z),minQ=APPARATUS_APOTHEM+radius;if(b.q>=minQ||b.q<=APPARATUS_APOTHEM)return false;const push=minQ-b.q;position.x+=b.nx*push;position.z+=b.nz*push;const vn=velocity.x*b.nx+velocity.z*b.nz;if(vn<0){velocity.x-=(1+restitution)*vn*b.nx;velocity.z-=(1+restitution)*vn*b.nz}velocity.x*=drag;velocity.z*=drag;return true;}
  function segmentApparatusHit(a,b){let enter=0,exit=1,normal=null;const d=b.clone().sub(a),slabs=PLANES.map(([nx,nz])=>({n:new THREE.Vector3(nx,0,nz),c:APPARATUS_APOTHEM}));slabs.push({n:new THREE.Vector3(0,1,0),c:APPARATUS_TOP},{n:new THREE.Vector3(0,-1,0),c:-APPARATUS_BOTTOM});for(const s of slabs){const da=s.n.dot(a)-s.c,dd=s.n.dot(d);if(Math.abs(dd)<1e-8){if(da>0)return null;continue}const t=-da/dd;if(dd<0){if(t>enter){enter=t;normal=s.n}}else exit=Math.min(exit,t);if(enter>exit)return null}return enter>=0&&enter<=1&&normal?{t:enter,point:a.clone().lerp(b,enter),normal:normal.clone()}:null;}
  rebuild();
  return{mesh,apparatus,field,rebuild,dent,bite,crater,reset,groundHeight,terrainHeight,insideMaterial,insideApparatus,collideSphere,segmentApparatusHit,inspect:()=>({grid:[NX,NY,NZ],triangles,apparatus:{radius:APPARATUS_RADIUS,top:APPARATUS_TOP,bottom:APPARATUS_BOTTOM},materialApothem:MATERIAL_APOTHEM})};
}